spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerceDB1
server.port=7000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=navyy223344@gmail.com
spring.mail.password=wbnpjlouhbxyvwgj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true